### ISSUE TITLE
Remove please

### ISSUE THREAD

**Issue by danielgrimshaw** [ZachOhara/Robot-API#3]
@ZachOhara 
There have been three votes against having this as a repo on the Thunderbots-5604 account.
You have until Friday to remove it. The copy on this organization will be deleted at 6:20 AM PST on Friday 1/16/15 if not earlier.

**Comment by ZachOhara** [comment]
Done

**Comment by ZachOhara** [comment]
Please see the issue I made in the 2015-code repo @danielgrimshaw
